---
- hosts: vyos
  gather_facts: no
  connection: local

  vars:
    limit_to: "*"
    debug: false

# Run the tests within blocks allows the the next module to be tested if the previous one fails.
# This is done to allow https://github.com/ansible/dci-partner-ansible/ to run the full set of tests.


  tasks:
    - set_fact:
        test_failed: false
    - block:
      - include_role:
          name: vyos_command
        when: "limit_to in ['*', 'vyos_command']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_config
        when: "limit_to in ['*', 'vyos_config']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_user
        when: "limit_to in ['*', 'vyos_user']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_banner
        when: "limit_to in ['*', 'vyos_banner']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_linkagg
        when: "limit_to in ['*', 'vyos_linkagg']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_static_route
        when: "limit_to in ['*', 'vyos_static_route']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_l3_interface
        when: "limit_to in ['*', 'vyos_l3_interface']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_logging
        when: "limit_to in ['*', 'vyos_logging']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_lldp
        when: "limit_to in ['*', 'vyos_lldp']"
      rescue:
        - set_fact: test_failed=true

    - block:
      - include_role:
          name: vyos_lldp_interface
        when: "limit_to in ['*', 'vyos_lldp_interface']"
      rescue:
        - set_fact: test_failed=true


###########
    - name: Has any previous test failed?
      fail:
        msg: "One or more tests failed, check log for details"
      when: test_failed
